import { GoogleGenAI, Modality } from "@google/genai";

// The API key is injected from the environment.
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || process.env.API_KEY });

const model = 'gemini-2.5-flash-image';

const fileToGenerativePart = (base64, mimeType) => {
  return {
    inlineData: {
      data: base64,
      mimeType,
    },
  };
};

const handleApiError = (error) => {
    console.error("Error generating image with Gemini API:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("An unknown error occurred while generating the image.");
};

export const generateFittingRoomImage = async (
  personImage,
  clothingImage
) => {
  const prompt = `
    Your task is to digitally dress a person from one image with an item of clothing from another.
    1. Analyze the first image, which contains a person.
    2. Analyze the second image, which contains an article of clothing.
    3. Generate a new image where the person is wearing the clothing from the second image.
    IMPORTANT: You must *only* replace the clothing on the person that corresponds to the item in the second image.
    Preserve everything else from the first image with extreme accuracy: the person's pose, facial features, body shape, hair, and the background must not be altered in any way.
    The final image must be photorealistic and seamless.
  `;

  try {
    const personPart = fileToGenerativePart(personImage.base64, personImage.mimeType);
    const clothingPart = fileToGenerativePart(clothingImage.base64, clothingImage.mimeType);

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          personPart,
          clothingPart,
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }

    throw new Error("No image was generated by the API. The response may have been blocked.");

  } catch (error) {
    handleApiError(error);
  }
};


export const generateImageFromTextPrompt = async (
  personImage,
  textPrompt
) => {
  const prompt = `
    Your task is to digitally change the clothing of a person in an image based on a text description.
    1. Analyze the provided image of a person.
    2. Read the text description of the desired clothing: "${textPrompt}".
    3. Generate a new image where the person is wearing clothing that perfectly matches the text description.
    IMPORTANT: You must *only* change the person's clothing.
    Preserve everything else from the original image with extreme accuracy: the person's pose, facial features, body shape, hair, and the background must not be altered in any way.
    The final image must be photorealistic, high-quality, and seamless.
  `;

  try {
    const personPart = fileToGenerativePart(personImage.base64, personImage.mimeType);

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          personPart,
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }

    throw new Error("No image was generated by the API. The response may have been blocked.");
  } catch (error) {
    handleApiError(error);
  }
};

export const generateSceneFromTextPrompt = async (
  personImage,
  textPrompt
) => {
  const prompt = `
    Your task is to edit an image based on a user's text description of the desired changes.
    1. Analyze the provided original image.
    2. Read the user's instructions for changes: "${textPrompt}".
    3. Generate a new image by applying *only* the specific changes described in the text. These changes might involve the background, environment, camera angle, lighting, or overall style.
    IMPORTANT: Do not make any changes that are not explicitly requested in the prompt.
    It is absolutely crucial to preserve the person in the image (including their appearance, clothing, and pose) as accurately as possible, unless the prompt specifically instructs you to modify them.
    The resulting image must be realistic and high-quality.
  `;

  try {
    const personPart = fileToGenerativePart(personImage.base64, personImage.mimeType);

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          personPart,
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }

    throw new Error("No image was generated by the API. The response may have been blocked.");
  } catch (error) {
    handleApiError(error);
  }
};

