// NanoBanana API Service
import { Buffer } from 'buffer';

const apiKey = process.env.NANOBANANA_API_KEY || '909a15ea092c13dabaa121e96c0470d9';
const apiBaseUrl = process.env.NANOBANANA_API_URL || 'https://api.nanobanana.com/v1';

if (!apiKey) {
  console.error('NANOBANANA_API_KEY is not set in environment variables');
  throw new Error('NANOBANANA_API_KEY environment variable is required');
}

console.log(`Using нанабанана API`);

const handleApiError = (error) => {
    console.error("Error generating image with нанабанана API:", error);
    
    if (error?.response) {
        const status = error.response.status;
        const data = error.response.data;
        
        // Quota exceeded (429)
        if (status === 429) {
            throw new Error(
                `Превышена квота API. На бесплатном тарифе нанабанана API есть ограничения.\n\n` +
                `Попробуйте снова позже или перейдите на платный тариф.`
            );
        }
        
        // Other API errors
        if (data?.error || data?.message) {
            throw new Error(`Ошибка API: ${data.error || data.message}`);
        }
        
        throw new Error(`Ошибка API: HTTP ${status}`);
    }
    
    // Standard Error objects
    if (error instanceof Error) {
        if (error.message.includes('Превышена квота') || error.message.includes('квота')) {
            throw error;
        }
        throw new Error(`Ошибка генерации изображения: ${error.message}`);
    }
    
    throw new Error("Произошла неизвестная ошибка при генерации изображения.");
};

// Helper to convert base64 to data URL
const base64ToDataUrl = (base64, mimeType) => {
    return `data:${mimeType};base64,${base64}`;
};

export const generateFittingRoomImage = async (
  personImage,
  clothingImage
) => {
  const prompt = `
    Your task is to digitally dress a person from one image with an item of clothing from another.
    1. Analyze the first image, which contains a person.
    2. Analyze the second image, which contains an article of clothing.
    3. Generate a new image where the person is wearing the clothing from the second image.
    IMPORTANT: You must *only* replace the clothing on the person that corresponds to the item in the second image.
    Preserve everything else from the first image with extreme accuracy: the person's pose, facial features, body shape, hair, and the background must not be altered in any way.
    The final image must be photorealistic and seamless.
  `;

  try {
    const personDataUrl = base64ToDataUrl(personImage.base64, personImage.mimeType);
    const clothingDataUrl = base64ToDataUrl(clothingImage.base64, clothingImage.mimeType);

    const response = await fetch(`${apiBaseUrl}/generate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: prompt,
        person_image: personDataUrl,
        clothing_image: clothingDataUrl,
        task: 'fitting_room'
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw { response: { status: response.status, data: errorData } };
    }

    const data = await response.json();
    
    // Extract base64 image from response
    // Response format may vary, try common patterns
    if (data.image) {
      // If image is base64 string
      if (typeof data.image === 'string') {
        // Remove data URL prefix if present
        return data.image.includes(',') ? data.image.split(',')[1] : data.image;
      }
    }
    
    if (data.image_url) {
      // If image is URL, fetch it and convert to base64
      const imageResponse = await fetch(data.image_url);
      const arrayBuffer = await imageResponse.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      return buffer.toString('base64');
    }
    
    if (data.data) {
      // If data is base64
      return data.data.includes(',') ? data.data.split(',')[1] : data.data;
    }

    throw new Error("No image was generated by the API. Unexpected response format.");
  } catch (error) {
    console.error('Full error object:', JSON.stringify(error, null, 2));
    handleApiError(error);
  }
};

export const generateImageFromTextPrompt = async (
  personImage,
  textPrompt
) => {
  const prompt = `
    Your task is to digitally change the clothing of a person in an image based on a text description.
    1. Analyze the provided image of a person.
    2. Read the text description of the desired clothing: "${textPrompt}".
    3. Generate a new image where the person is wearing clothing that perfectly matches the text description.
    IMPORTANT: You must *only* change the person's clothing.
    Preserve everything else from the original image with extreme accuracy: the person's pose, facial features, body shape, hair, and the background must not be altered in any way.
    The final image must be photorealistic, high-quality, and seamless.
  `;

  try {
    const personDataUrl = base64ToDataUrl(personImage.base64, personImage.mimeType);

    const response = await fetch(`${apiBaseUrl}/generate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: prompt,
        person_image: personDataUrl,
        text_prompt: textPrompt,
        task: 'text_prompt'
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw { response: { status: response.status, data: errorData } };
    }

    const data = await response.json();
    
    if (data.image) {
      if (typeof data.image === 'string') {
        return data.image.includes(',') ? data.image.split(',')[1] : data.image;
      }
    }
    
    if (data.image_url) {
      const imageResponse = await fetch(data.image_url);
      const arrayBuffer = await imageResponse.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      return buffer.toString('base64');
    }
    
    if (data.data) {
      return data.data.includes(',') ? data.data.split(',')[1] : data.data;
    }

    throw new Error("No image was generated by the API. Unexpected response format.");
  } catch (error) {
    console.error('Full error object:', JSON.stringify(error, null, 2));
    handleApiError(error);
  }
};

export const generateSceneFromTextPrompt = async (
  personImage,
  textPrompt
) => {
  const prompt = `
    Your task is to edit an image based on a user's text description of the desired changes.
    1. Analyze the provided original image.
    2. Read the user's instructions for changes: "${textPrompt}".
    3. Generate a new image by applying *only* the specific changes described in the text. These changes might involve the background, environment, camera angle, lighting, or overall style.
    IMPORTANT: Do not make any changes that are not explicitly requested in the prompt.
    It is absolutely crucial to preserve the person in the image (including their appearance, clothing, and pose) as accurately as possible, unless the prompt specifically instructs you to modify them.
    The resulting image must be realistic and high-quality.
  `;

  try {
    const personDataUrl = base64ToDataUrl(personImage.base64, personImage.mimeType);

    const response = await fetch(`${apiBaseUrl}/generate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: prompt,
        person_image: personDataUrl,
        text_prompt: textPrompt,
        task: 'scene_edit'
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw { response: { status: response.status, data: errorData } };
    }

    const data = await response.json();
    
    if (data.image) {
      if (typeof data.image === 'string') {
        return data.image.includes(',') ? data.image.split(',')[1] : data.image;
      }
    }
    
    if (data.image_url) {
      const imageResponse = await fetch(data.image_url);
      const arrayBuffer = await imageResponse.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      return buffer.toString('base64');
    }
    
    if (data.data) {
      return data.data.includes(',') ? data.data.split(',')[1] : data.data;
    }

    throw new Error("No image was generated by the API. Unexpected response format.");
  } catch (error) {
    console.error('Full error object:', JSON.stringify(error, null, 2));
    handleApiError(error);
  }
};

